title: Brian Kovacik 
occupation: Frontend/Full stack Software Engineer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown

contact:
  - type: github
    data: http://www.github.com/bkovacik
  - type: email 
    data: brian3kovacik@gmail.com
    link: mailto:brian3kovacik@gmail.com
  - type: phone
    data: (925)-856-7215
  - type: linkedin
    data: https://www.linkedin.com/in/brian-kovacik-853b64111

newline: >
 .

collections:
  assets:
  projects:
    output: true
